### ISSUE TITLE
Multiple tab objects not possible

### ISSUE THREAD

**Issue by CattyPus** [balexbyrd/sense-Tabs#1]
First of all, this is such a great extension and it is beyond me QS does not have this by default.

The only problem I have is, that i cannot make multiple tab objects, i.e. if I make one tab object with some master items there is no problem, but if I make a second one, this will overwrite the first tab objects tabs.

**Comment by balexbyrd** [comment]
CattyPus (awesome name btw), I got you covered. I'll put in some work and will update the repo. when completed.

Thanks for the compliment! I hope they're busy integrating alternate states into QS, I'll handle the low hanging fruit.

**Comment by balexbyrd** [comment]
The code has been updated, please re-import and take her for a spin. If you could, follow up so I can close out the issue. Thanks!

**Comment by CattyPus** [comment]
Works like a charm! Thanks for the quick response, and for your time!
