### ISSUE TITLE
Extension loads outdated jQuery 1.11.0

### ISSUE THREAD

**Issue by npgeomap** [balexbyrd/sense-Tabs#4]
The "sense-Tabs" extension loads an old and pretty outdated jQuery 1.11.0 from Jan 2014. This is the reason why Qlik Sense becomes slow and has some inexplicable bevaviours to other Qlik Sense Objects after adding "sense-Tabs". 
There is no need to load the CDN hosted JQuery Version since Qlik Sense already loads and provides a more current Version.

**Comment by balexbyrd** [comment]
Updated to current release //code.jquery.com/jquery-3.1.1.min.js
